# Generated by Django 4.2.7 on 2023-12-29 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_background', models.CharField(max_length=100)),
                ('character_icon', models.CharField(max_length=100)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Characters.character')),
            ],
        ),
    ]
